'''
pave-the-planet
Mitchell Deevers ~ midchll
2026

obj.py
format export basic .obj file 
'''

from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
import os

import tkinter as tk
from tkinter import filedialog


@dataclass
class OBJFile:
    path: str
    name: str
    content: list[str] = field(default_factory=list[str])
    
    
def count_feats(lines:list[str]) -> dict[str,int]:
    '''Count number of vertices and faces in obj content'''
    feats = {'v': 0, 'f': 0}
    
    for line in lines:
        if line[0] not in 'vf':
            continue
        
        l = [x.strip() for x in line.split()]

        if l[0] == 'v':
            feats['v'] += 1
        if l[0] == 'f':
            feats['f'] += 1
    
    return feats

    
def write_obj(content:list[str], name:str|None=None, path:str|None=None, ) -> OBJFile:
    '''Write obj content to file'''
    feats = count_feats(content)
    cont = [
        f'# obj file generated by pave-the-planet ~ {date.today().strftime("%m/%d/%Y")}\n',
        f'# verts = {feats['v']}\n'
        f'# faces = {feats['f']}\n'
        '#\n\n'
    ]
    
    for l in content:
        if len(l) >= 2 and l[:-2] != '\n':
            cont.append(l + '\n')
    
    if not path:
        root = tk.Tk()
        root.withdraw()
        d_path = Path(filedialog.askdirectory(title='Select save directory', initialdir=os.curdir, mustexist=True))

    f_name = name or f'ptp_obj_{sum(1 for item in d_path.iterdir() if item.is_file())}'
    d_path = os.path.join(path or d_path, f_name) + '.obj'
    
    f = OBJFile(
        name = f_name,
        path = d_path,
        content = cont
    )
    
    with open(f.path, 'w') as file:
        try:
            file.writelines(cont)
        except:
            print('ERROR WRITING OBJ')
        
    return f